description = "Ubi 8 base image with buildpacks for Node.js"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nodejs:1.4.0"
  version = "1.4.0"

[lifecycle]
  version = "0.17.0-pre.2"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "1.4.0"

[[extensions]]
  id = "redhat-runtimes/nodejs"
  version = "0.0.1"
  uri = "docker://gcr.io/paketo-community/ubi-nodejs-extension:0.0.1"

[[order-extensions]]
  [[order-extensions.group]]
    id = "redhat-runtimes/nodejs"
    version = "0.0.1"

[stack]
  id = "io.buildpacks.stacks.ubi8"
  build-image = "docker.io/paketocommunity/build-ubi-base/build:0.0.1"
  run-image = "index.docker.io/paketocommunity/run-ubi-base:0.0.1"
  run-image-mirrors = ["gcr.io/paketocommunity/run-ubi-base:0.0.1"]
